const STATUS = {
  ACTIVE: "ACTIVE",
  LOCKED: "LOCKED",
  HIDDEN: "HIDDEN",
  MAINTENANCE: "MAINTENANCE",
  CANCELLED: "CANCELLED",
  FINISHED: "FINISHED",
  AVAILABLE: "AVAILABLE",
  HELD: "HELD",
  SOLD: "SOLD",
  PENDING: "PENDING",
  PAID: "PAID",
  EXPIRED: "EXPIRED",
  CHECKED_IN: "CHECKED_IN",
  INACTIVE: "INACTIVE",
  SHOWING: "NOW_SHOWING",
  COMING_SOON: "COMING_SOON",
  STOPPED: "STOPPED",
};

module.exports = STATUS;
